/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Verify that the API and database are responding.
         *     Without the database no endpoint can serve anything useful, so an
         *     unreachable database means the whole service is in error, not degraded.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingredients
         * @description Retrieve a list of all ingredients in the bakery's inventory.
         */
        get: operations["get_ingredients_api_v1_ingredients__get"];
        put?: never;
        /**
         * Create Ingredient
         * @description Create a new ingredient in the inventory.
         *
         *     UI Note: On successful creation, the frontend should show a success toast
         *     and redirect the user to 'products_list'.
         */
        post: operations["create_ingredient_api_v1_ingredients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients/{ingredient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingredient By Id
         * @description Retrieve a specific ingredient by its unique ID.
         *
         *     UI Note: If this returns a 404, the frontend should display a 'Not Found'
         *     message and provide a 'Back' or 'Cancel' button routing to 'products_list'.
         */
        get: operations["get_ingredient_by_id_api_v1_ingredients__ingredient_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Ingredient
         * @description Delete an ingredient from the inventory.
         *
         *     UI Note: On successful deletion (204), remove the item from the local
         *     state or refetch the list, and ensure the user is on 'products_list'.
         */
        delete: operations["delete_ingredient_api_v1_ingredients__ingredient_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Ingredient
         * @description Partially update an existing ingredient in the inventory.
         *
         *     UI Note: On successful update or if the user clicks 'Cancel',
         *     the frontend should redirect to the 'products_list' route.
         */
        patch: operations["update_ingredient_api_v1_ingredients__ingredient_id__patch"];
        trace?: never;
    };
    "/api/v1/ingredients/{ingredient_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reactivate Ingredient
         * @description Reactivate a previously deleted ingredient.
         */
        patch: operations["reactivate_ingredient_api_v1_ingredients__ingredient_id__reactivate_patch"];
        trace?: never;
    };
    "/api/v1/recipes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipes
         * @description Retrieve a list of all ACTIVE recipes.
         */
        get: operations["get_recipes_api_v1_recipes__get"];
        put?: never;
        /**
         * Create Recipe
         * @description Create a new recipe in the inventory.
         *
         *     UI Note: On successful creation, the frontend should show a success toast
         *     and redirect the user to 'recipes_list'.
         */
        post: operations["create_recipe_api_v1_recipes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipe By Id
         * @description Retrieve a specific recipe by its unique ID.
         *
         *     UI Note: If this returns a 404, the frontend should display a 'Not Found'
         *     message and provide a 'Back' or 'Cancel' button routing to 'recipes_list'.
         */
        get: operations["get_recipe_by_id_api_v1_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Recipe
         * @description Delete a recipe from the inventory.
         *
         *     UI Note: On successful deletion (204), remove the item from the local
         *     state or refetch the list, and ensure the user is on 'recipes_list'.
         */
        delete: operations["delete_recipe_api_v1_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Recipe
         * @description Partially update an existing recipe in the inventory.
         *
         *     UI Note: On successful update or if the user clicks 'Cancel',
         *     the frontend should redirect to the 'recipes_list' route.
         */
        patch: operations["update_recipe_api_v1_recipes__recipe_id__patch"];
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reactivate Recipe
         * @description Reactivate a previously deleted recipe.
         */
        patch: operations["reactivate_recipe_api_v1_recipes__recipe_id__reactivate_patch"];
        trace?: never;
    };
    "/api/v1/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Products
         * @description Retrive a list of all products
         */
        get: operations["get_products_api_v1_products__get"];
        put?: never;
        /**
         * Create Product
         * @description Create a new product and link it to an existing recipe.
         *
         *     UI Note: On successful creation (201), redirect the user to 'products_list'
         *     or clear the form for a new entry.
         */
        post: operations["create_product_api_v1_products__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product By Id
         * @description Retrieve a specific product by its unique ID.
         *
         *     UI Note: If this returns a 404, the frontend should display a 'Not Found'
         *     message and provide a 'Back' or 'Cancel' button routing to 'products_list'.
         */
        get: operations["get_product_by_id_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Product
         * @description Delete a product from the inventory.
         *
         *     UI Note: On successful deletion (204), remove the item from the local
         *     state or refetch the list, and ensure the user is on 'products_list'.
         */
        delete: operations["delete_product_api_v1_products__product_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Product
         * @description Partially update an existing Product in the inventory.
         *
         *     UI Note: On successful update or if the user clicks 'Cancel',
         *     the frontend should redirect to the 'products_list' route.
         */
        patch: operations["update_product_api_v1_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/products/{product_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reactivate Product */
        patch: operations["reactivate_product_api_v1_products__product_id__reactivate_patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngredientCategory
         * @enum {string}
         */
        IngredientCategory: "lacteos" | "secos" | "liquidos" | "frutas_verduras" | "especias";
        /** IngredientCreate */
        IngredientCreate: {
            /** Name */
            name: string;
            /** Stock Quantity */
            stock_quantity: number;
            unit: components["schemas"]["MeasurementUnit"];
            category: components["schemas"]["IngredientCategory"];
            /** Current Unit Price */
            current_unit_price: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** IngredientResponse */
        IngredientResponse: {
            /** Name */
            name: string;
            /** Stock Quantity */
            stock_quantity: number;
            unit: components["schemas"]["MeasurementUnit"];
            category: components["schemas"]["IngredientCategory"];
            /** Current Unit Price */
            current_unit_price: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
        };
        /** IngredientUpdate */
        IngredientUpdate: {
            /** Name */
            name?: string | null;
            /** Stock Quantity */
            stock_quantity?: number | null;
            unit?: components["schemas"]["MeasurementUnit"] | null;
            category?: components["schemas"]["IngredientCategory"] | null;
            /** Current Unit Price */
            current_unit_price?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * MeasurementUnit
         * @enum {string}
         */
        MeasurementUnit: "kg" | "g" | "l" | "ml" | "pza" | "caja";
        /**
         * ProductCategory
         * @enum {string}
         */
        ProductCategory: "Pasteles" | "Rebanadas" | "Postes Individuales" | "Bebidas" | "Otros";
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Sale Price */
            sale_price: number;
            category: components["schemas"]["ProductCategory"];
            /** Recipe Id */
            recipe_id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ProductResponse */
        ProductResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Sale Price */
            sale_price: number;
            category: components["schemas"]["ProductCategory"];
            /** Recipe Id */
            recipe_id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /** Cost */
            cost?: number | null;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Sale Price */
            sale_price?: number | null;
            category?: components["schemas"]["ProductCategory"] | null;
            /** Recipe Id */
            recipe_id?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** RecipeCreate */
        RecipeCreate: {
            /** Name */
            name: string;
            /** Instructions */
            instructions: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Ingredients */
            ingredients: components["schemas"]["RecipeIngredientCreate"][];
        };
        /** RecipeIngredientCreate */
        RecipeIngredientCreate: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Quantity */
            quantity: number;
        };
        /** RecipeIngredientResponse */
        RecipeIngredientResponse: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Quantity */
            quantity: number;
            /** Ingredient Name */
            ingredient_name: string;
            /** Ingredient Unit */
            ingredient_unit: string;
        };
        /** RecipeIngredientUpdate */
        RecipeIngredientUpdate: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Quantity */
            quantity: number;
        };
        /** RecipeResponse */
        RecipeResponse: {
            /** Name */
            name: string;
            /** Instructions */
            instructions: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /** Ingredients */
            ingredients: components["schemas"]["RecipeIngredientResponse"][];
        };
        /** RecipeUpdate */
        RecipeUpdate: {
            /** Name */
            name?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Ingredients */
            ingredients?: components["schemas"]["RecipeIngredientUpdate"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_ingredients_api_v1_ingredients__get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ingredient_api_v1_ingredients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredient_by_id_api_v1_ingredients__ingredient_id__get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ingredient_api_v1_ingredients__ingredient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ingredient_api_v1_ingredients__ingredient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_ingredient_api_v1_ingredients__ingredient_id__reactivate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipes_api_v1_recipes__get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_api_v1_recipes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_by_id_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_api_v1_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_api_v1_recipes__recipe_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_recipe_api_v1_recipes__recipe_id__reactivate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_api_v1_products__get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_by_id_api_v1_products__product_id__get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_product_api_v1_products__product_id__reactivate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
